# Generated by Django 2.1.5 on 2019-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('LName', models.CharField(default='', max_length=200)),
                ('Fonction', models.CharField(default='', max_length=200)),
                ('Profil', models.FileField(blank=True, null=True, upload_to='Profil/')),
                ('Adresse', models.CharField(default='', max_length=200)),
                ('Naissance', models.CharField(default='', max_length=200)),
                ('Lieu', models.CharField(default='', max_length=200)),
                ('Commune', models.CharField(default='', max_length=200)),
                ('Departement', models.CharField(default='', max_length=200)),
                ('Sexe', models.CharField(default='', max_length=200)),
                ('Statut', models.CharField(default='', max_length=200)),
                ('Dependant', models.CharField(default='', max_length=200)),
                ('Telephone_1', models.CharField(default='', max_length=200)),
                ('Telephone_2', models.CharField(default='', max_length=200)),
                ('Email', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
